version: '3'

tasks:
  build:
    desc: Build the Go app
    cmds:
      - go build -o app main.go

  run:
    desc: Run the Go app
    cmds:
      - task: build
      - ./app

  test:
    desc: Run tests for the Go app
    cmds:
      - go test ./...
